In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [2]:
website = 'https://www.cars.com/shopping/results/?stock_type=cpo&makes%5B%5D=mercedes_benz&models%5B%5D=&list_price_max=&maximum_distance'

In [4]:
response=requests.get(website)
response.status_code

200

In [5]:
soup = BeautifulSoup(response.content, 'html.parser')

In [6]:
results = soup.find_all('div', {'class' : 'vehicle-card'})

In [7]:
len(results)

21

In [8]:
#carname
results[0].find('h2').get_text()

'2021 Mercedes-Benz AMG GT 63 4-Door'

In [9]:
#mileage
results[0].find('div', {'class':'mileage'}).get_text()

'11,016 mi.'

In [10]:
#price
results[0].find('span', {'class':'primary-price'}).get_text()

'$119,900'

In [11]:
#rating
results[0].find('span', {'class':'sds-rating__count'}).get_text()

'4.2'

In [12]:
#review count
results[0].find('span', {'class':'sds-rating__link'}).get_text()

'(1,797 reviews)'

In [13]:
#dealer name
results[0].find('div', {'class':'dealer-name'}).get_text().strip()

'Mercedes-Benz of Wilmington'

In [14]:
name = []
mileage = []
price = []
dealer_name = []
rating = []
review_count = []
dealer_name = []

for result in results:
    
    # name
    try:
        name.append(result.find('h2').get_text()) 
    except:
        name.append('n/a')
    
    # mileage
    try:
        mileage.append(result.find('div', {'class':'mileage'}).get_text())
    except:
        mileage.append('n/a')
        
    #price 
    try:
        price.append(result.find('span', {'class':'primary-price'}).get_text())
    except:
        price.append('n/a')
        
    # rating
    try:
        rating.append(result.find('span', {'class':'sds-rating__count'}).get_text())
    except:
        rating.append('n/a')
    
    # review_count
    try:
        review_count.append(result.find('span', {'class':'sds-rating__link'}).get_text())
    except:
        review_count.append('n/a')
        
    # dealer_name
    try:
        dealer_name.append(result.find('div', {'class':'dealer-name'}).get_text().strip())
    except:
        dealer_name.append('n/a')

In [15]:
# dictionary
car_dealer = pd.DataFrame({'Name': name, 'Mileage':mileage, 'Dealer Name':dealer_name,
                                'Rating': rating, 'Review Count': review_count, 'Price': price})

In [16]:
car_dealer

,Name,Mileage,Dealer Name,Rating,Review Count,Price
0,2021 Mercedes-Benz AMG GT 63 4-Door,"11,016 mi.",Mercedes-Benz of Wilmington,4.2,"(1,797 reviews)","$119,900"
1,2021 Mercedes-Benz AMG E 63 S 4MATIC,"26,462 mi.",Mercedes-Benz of Louisville,4.5,(991 reviews),"$94,754"
2,2021 Mercedes-Benz AMG GT 43 Base,"36,896 mi.",Mercedes-Benz of North Olmsted,4.8,"(1,538 reviews)","$67,923"
3,2023 Mercedes-Benz AMG C 43 Base 4MATIC,"2,423 mi.",Jackie Cooper Imports,4.9,"(4,477 reviews)","$62,000"
4,2023 Mercedes-Benz AMG GLE 53 Base,"15,177 mi.",Mercedes-Benz of Tuscaloosa,n/a,(15 reviews),"$73,972"
5,2022 Mercedes-Benz GLE 350 Base 4MATIC,"26,743 mi.",Euro Motorcars Devon,4.1,(344 reviews),"$55,389"
6,2024 Mercedes-Benz GLE 350 Base 4MATIC,"1,693 mi.",Mercedes-Benz of Fort Washington,4.6,"(3,138 reviews)","$67,254"
7,2024 Mercedes-Benz GLE 450 4MATIC,"3,209 mi.",Mercedes-Benz Doylestown,4.3,(55 reviews),"$74,118"
8,2022 Mercedes-Benz AMG GT 53 Base,"6,715 mi.",Mercedes-Benz of Jackson,4.1,(821 reviews),"$90,325"
9,2020 Mercedes-Benz C-Class C 300,"65,935 mi.",Mercedes-Benz of Jackson,4.1,(821 reviews),"$24,345"
10,2019 Mercedes-Benz E-Class E 300,"20,864 mi.",Mercedes-Benz of Orange County NY,4.5,(523 reviews),"$35,491"
11,2024 Mercedes-Benz GLE 450 4MATIC,"5,453 mi.",Mercedes-Benz of Orange County NY,4.5,(523 reviews),"$76,987"
12,2021 Mercedes-Benz E-Class E 350 4MATIC,"43,860 mi.",Mercedes-Benz of White Plains,4.3,"(1,647 reviews)","$37,534"
13,2021 Mercedes-Benz GLS 450 4MATIC,"45,480 mi.",Mercedes-Benz of Springfield,4.6,(110 reviews),"$54,497"
14,2019 Mercedes-Benz GLC 300 Base 4MATIC,"18,634 mi.",Mercedes-Benz of Springfield,4.6,(110 reviews),"$29,644"
15,2023 Mercedes-Benz AMG GLS 63 Base 4MATIC,"8,519 mi.",Mercedes-Benz of Houston Greenway,4.7,"(2,899 reviews)","$136,450"
16,2021 Mercedes-Benz GLS 450 4MATIC,"44,000 mi.",Mercedes-Benz of West Houston,4.6,(76 reviews),"$55,993"
17,2020 Mercedes-Benz S-Class S 450,"38,752 mi.",Mercedes-Benz of West Houston,4.6,(76 reviews),"$52,994"
18,2020 Mercedes-Benz S-Class S 450,"23,232 mi.",Mercedes-Benz of West Houston,4.6,(76 reviews),"$54,996"
19,2023 Mercedes-Benz EQS 580 Base 4MATIC,"6,776 mi.",Mercedes-Benz of Naples,4.8,"(1,559 reviews)","$87,487"
20,2018 Mercedes-Benz S-Class S 560,"58,846 mi.",Mercedes-Benz of Coconut Creek,4.5,"(1,475 reviews)","$44,995"

In [17]:
car_dealer['Review Count'] = car_dealer['Review Count'].apply(lambda x: x.strip('reviews)').strip('('))

In [18]:
# dataframe updated
car_dealer

,Name,Mileage,Dealer Name,Rating,Review Count,Price
0,2021 Mercedes-Benz AMG GT 63 4-Door,"11,016 mi.",Mercedes-Benz of Wilmington,4.2,"1,797","$119,900"
1,2021 Mercedes-Benz AMG E 63 S 4MATIC,"26,462 mi.",Mercedes-Benz of Louisville,4.5,991,"$94,754"
2,2021 Mercedes-Benz AMG GT 43 Base,"36,896 mi.",Mercedes-Benz of North Olmsted,4.8,"1,538","$67,923"
3,2023 Mercedes-Benz AMG C 43 Base 4MATIC,"2,423 mi.",Jackie Cooper Imports,4.9,"4,477","$62,000"
4,2023 Mercedes-Benz AMG GLE 53 Base,"15,177 mi.",Mercedes-Benz of Tuscaloosa,n/a,15,"$73,972"
5,2022 Mercedes-Benz GLE 350 Base 4MATIC,"26,743 mi.",Euro Motorcars Devon,4.1,344,"$55,389"
6,2024 Mercedes-Benz GLE 350 Base 4MATIC,"1,693 mi.",Mercedes-Benz of Fort Washington,4.6,"3,138","$67,254"
7,2024 Mercedes-Benz GLE 450 4MATIC,"3,209 mi.",Mercedes-Benz Doylestown,4.3,55,"$74,118"
8,2022 Mercedes-Benz AMG GT 53 Base,"6,715 mi.",Mercedes-Benz of Jackson,4.1,821,"$90,325"
9,2020 Mercedes-Benz C-Class C 300,"65,935 mi.",Mercedes-Benz of Jackson,4.1,821,"$24,345"
10,2019 Mercedes-Benz E-Class E 300,"20,864 mi.",Mercedes-Benz of Orange County NY,4.5,523,"$35,491"
11,2024 Mercedes-Benz GLE 450 4MATIC,"5,453 mi.",Mercedes-Benz of Orange County NY,4.5,523,"$76,987"
12,2021 Mercedes-Benz E-Class E 350 4MATIC,"43,860 mi.",Mercedes-Benz of White Plains,4.3,"1,647","$37,534"
13,2021 Mercedes-Benz GLS 450 4MATIC,"45,480 mi.",Mercedes-Benz of Springfield,4.6,110,"$54,497"
14,2019 Mercedes-Benz GLC 300 Base 4MATIC,"18,634 mi.",Mercedes-Benz of Springfield,4.6,110,"$29,644"
15,2023 Mercedes-Benz AMG GLS 63 Base 4MATIC,"8,519 mi.",Mercedes-Benz of Houston Greenway,4.7,"2,899","$136,450"
16,2021 Mercedes-Benz GLS 450 4MATIC,"44,000 mi.",Mercedes-Benz of West Houston,4.6,76,"$55,993"
17,2020 Mercedes-Benz S-Class S 450,"38,752 mi.",Mercedes-Benz of West Houston,4.6,76,"$52,994"
18,2020 Mercedes-Benz S-Class S 450,"23,232 mi.",Mercedes-Benz of West Houston,4.6,76,"$54,996"
19,2023 Mercedes-Benz EQS 580 Base 4MATIC,"6,776 mi.",Mercedes-Benz of Naples,4.8,"1,559","$87,487"
20,2018 Mercedes-Benz S-Class S 560,"58,846 mi.",Mercedes-Benz of Coconut Creek,4.5,"1,475","$44,995"

In [20]:
car_dealer.to_excel('car_dealer_single_page.xlsx', index=False)

In [22]:
# write into csv
cars_df = pd.DataFrame(car_dealer)
csv_file_name = 'car_dealer_single_page.csv'
cars_df.to_csv(csv_file_name, index=False)